name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # Setup SSH private key
      - name: Create SSH private key
        run: |
          mkdir -p "$HOME/.ssh"
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > "$HOME/.ssh/authorized_keys"
          chmod 600 "$HOME/.ssh/authorized_keys"

      # Deploy using rsync
      - name: Deploy files
        run: |
          rsync -e "ssh -p 22 -i $HOME/.ssh/authorized_keys -o StrictHostKeyChecking=no" \
            --archive --compress --delete \
            --exclude "wp-config.php" \
            --exclude "wp-content/uploads" \
            --exclude "wp-content/plugins" \
            . \
            strizhki@185.137.235.119:/var/www/strizhki/data/www/abedul.stage.ibessonniy.ru
